# Generated by Django 4.2.1 on 2023-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="graduated_from",
            field=models.CharField(
                choices=[
                    ("POLY", "Bahr Dar Polytechnic Institute"),
                    ("PEDA", "Bahr Dar Pedagogy"),
                    ("BDU", "Bahr Dar University"),
                ],
                default="BDU",
                max_length=20,
            ),
        ),
    ]
